### ISSUE TITLE
Running task list

### ISSUE THREAD

**Issue by shreshthmohan** [shreshthmohan/nomad-notes#2]
- [x] tsv parsing 
- [ ] parsed data validation
  - [ ] number of columns 
  - [ ] invalid values
- [ ] Sanity checks
  - [ ] Values in °C won't exceed 52?
  - [ ] Does each place data have average high and average low temp row

**Comment by shreshthmohan** [comment]
test
